#!/usr/bin/env python3
"""Copies the Thanglish word lists from src/lib/thanglish-data.js into apps-script/Code.gs.
Run after editing the word lists:  python scripts/sync-thanglish.py"""
import json, os, subprocess, tempfile, re
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
entry = os.path.join(tempfile.gettempdir(), 'thanglish-dump.mjs')
out = os.path.join(tempfile.gettempdir(), 'thanglish-dump.cjs')
open(entry, 'w').write("import * as d from '%s';\nconsole.log(JSON.stringify(d));\n" % os.path.join(root, 'src/lib/thanglish-data.js').replace('\\', '/'))
subprocess.run(['npx', 'esbuild', entry, '--bundle', '--platform=node', '--outfile=' + out, '--log-level=error'], check=True, cwd=root, shell=os.name == 'nt')
data = json.loads(subprocess.run(['node', out], capture_output=True, text=True, check=True).stdout)
block = '// <thanglish-data> (generated by scripts/sync-thanglish.py — edit src/lib/thanglish-data.js instead)\n'
block += 'var TH_DATA = ' + json.dumps(data, ensure_ascii=False) + ';\n// </thanglish-data>'
gs_path = os.path.join(root, 'apps-script/Code.gs')
gs = open(gs_path, encoding='utf-8').read()
gs = re.sub(r'// <thanglish-data>.*?// </thanglish-data>', lambda m: block, gs, flags=re.S)
open(gs_path, 'w', encoding='utf-8').write(gs)
print('Code.gs updated:', len(data['PHRASES']), 'phrases,', len(data['WORDS']), 'words,', len(data['TYPOS']), 'typos')
